### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AffectedArc07** [AffectedArc07/ParaUtil#1]
- [x] Initial framework for both plugins and the DB
- [x] Ping handling
- [x] Basic login handling
- [x] Chat replacing usernames with ckeys
- [x] Automatic detection of ingame banned accounts
- [x] Sync with forum accounts for ingame permissions
- [x] Add a version reporting command
- [x] Port over tablist from my personal plugins

**Comment by hal9000PR** [comment]
Oh god don't replace my username with my ckey oh god oh fuck

**Comment by AffectedArc07** [comment]
> Oh god don't replace my username with my ckey oh god oh fuck

Too bad

**Comment by AffectedArc07** [comment]
And its ready
